export default [
  "Cicagna",
  "Sfruz",
  "Bergerac",
  "Wallasey",
  "Jauchelette",
  "Embourg",
  "Barahanagar",
  "Markham",
  "Allahabad",
  "Wambeek",
  "Beaufays",
  "Saarbrücken",
  "Blue Mountains",
  "Outremont",
  "Cambrai",
  "Tourcoing",
  "Panketal",
  "Meridian",
  "St. John's",
  "Ransart",
  "Mobile",
  "Isca sullo Ionio",
  "Moose Jaw",
  "Romano d'Ezzelino",
  "Aberdeen",
  "Vielsalm",
  "Zerba",
  "Bathurst",
  "Delta",
  "Monghidoro",
  "Draguignan",
  "LiŽge",
  "Courbevoie",
  "Duncan",
  "Traiguén",
  "Montignies-Saint-Christophe",
  "Sivry",
  "Tavigny",
  "Comblain-Fairon",
  "Etobicoke",
  "Mostazal",
  "Béthune",
  "Sgonico",
  "Bruderheim",
  "Boorsem",
  "Vilna",
  "Amroha",
  "Husum",
  "Aylesbury",
  "Ruvo del Monte",
  "Helchteren",
  "Castelmezzano",
  "Nederokkerzeel",
  "Ansfelden",
  "Avennes",
  "Kilwinning",
  "San Antonio",
  "Kelso",
  "Quenast",
  "Cádiz",
  "Bridgeport",
  "Meerle",
  "Bridgwater",
  "Brentwood",
  "Tourinne",
  "Pincher Creek",
  "Ham-sur-Heure",
  "Niterói",
  "Zaventem",
  "Aiello Calabro",
  "Amsterdam",
  "La Magdeleine",
  "Aisemont",
  "Meeuwen",
  "Bungay",
  "Port Lincoln",
  "Neuville",
  "Kirkland",
  "Banbury",
  "Crowsnest Pass",
  "Kaneohe",
  "Kortessem",
  "Township of Minden Hills",
  "Butzbach",
  "Aliano",
  "Rothesay",
  "Vauda Canavese",
  "Bihain",
  "Bodmin",
  "Burin",
  "Namur",
  "HŽvillers",
  "Puyehue",
  "Kilmalcolm",
  "Cunco",
  "Philadelphia",
  "Avellino",
  "San Marcello Pistoiese",
  "Grand-Leez"
];
